_wandb:
    value:
        cli_version: 0.23.0
        e:
            yzifxbqwycs629g2oepqx5bkdaudn1i8:
                codePath: Train.py
                codePathLocal: Train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "492739489792"
                        used: "209253961728"
                email: sunyanming18mtl@gmail.com
                executable: C:\Users\Yanming\anaconda3\envs\pytorch_gpu\python.exe
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-0ab7b3d0-587f-0b91-acbe-59d2f30fdbb8
                host: Qing
                memory:
                    total: "85798604800"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\Yanming\Desktop\M31_Project\Codes\ProstateCancerPrognosis3\Train.py
                python: CPython 3.13.9
                root: C:\Users\Yanming\Desktop\M31_Project\Codes\ProstateCancerPrognosis3
                startedAt: "2025-11-12T17:33:32.081544Z"
                writerId: yzifxbqwycs629g2oepqx5bkdaudn1i8
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
epochs:
    value: 15
